### ISSUE TITLE
[Bug] Reloading plugins

### ISSUE THREAD

**Issue by ericbarbwire** [rylinaux/PlugMan#17]
Hey guys, I've been using Plugman for a little bit over a year and for a very long time everything worked flawlessly, however, in recent months whenever I'd try to reload or load a plugin the server lag would pick up tremendously. I'm running Spigot build #27 currently.
Here is my latest timings report after I reloaded a plugin.
http://timings.aikar.co/?url=10361322
As you can see, Plugman is showing 
   0.01%	13,849.95%	  6.92 s	 6,924.98 ms	 0.0	       0.0k	    Command: plugman
Also, here is a pastebin of the latest console log at the time of this happening.
http://pastebin.com/HZfdKgZi
Thanks so much for reading sir :) Hopefully something can be done about this.

**Comment by rylinaux** [comment]
What plugin are you trying to reload?
