### ISSUE TITLE
Plugman Crash

### ISSUE THREAD

**Issue by sup3rn1nja** [rylinaux/PlugMan#18]
PlugMan crashes at startup.
http://pastebin.com/raw.php?i=GX2XRpdy

Plugman work on the PC but when I put it on a linux server, so it did not work.

**Comment by rylinaux** [comment]
It looks like you're running Java 6 on the Linux server, one of the requirements for PlugMan is Java 7.

**Comment by sup3rn1nja** [comment]
Thanks
